/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'surface-dim': '#dcd9d9',
        'on-primary-container': '#ff9d97',
        'inverse-primary': '#ffb3ae',
        'outline-variant': '#dfbfbd',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#2b1613',
        'tertiary-container': '#5c423d',
        'tertiary-fixed-dim': '#e3beb8',
        'surface-container-high': '#eae7e7',
        'inverse-on-surface': '#f3f0ef',
        'on-tertiary-fixed-variant': '#5b403c',
        'surface-container-highest': '#e4e2e1',
        'primary-fixed': '#ffdad7',
        'on-primary-fixed-variant': '#891c20',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1c1c',
        'inverse-surface': '#303030',
        'on-secondary-container': '#735700',
        'on-error': '#ffffff',
        'surface-container-low': '#f6f3f2',
        background: '#fcf9f8',
        'secondary-container': '#fece57',
        'on-tertiary-container': '#d3afa9',
        primary: '#6a020d',
        'primary-hover': '#9e2a2b',
        'primary-active': '#5e1315',
        'surface-tint': '#a93534',
        surface: '#fcf9f8',
        'secondary-fixed': '#ffdf98',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#5a4300',
        'on-background': '#1b1c1c',
        outline: '#8b716f',
        'surface-bright': '#fcf9f8',
        'tertiary-fixed': '#ffdad4',
        error: '#ba1a1a',
        'on-secondary-fixed': '#251a00',
        tertiary: '#442c28',
        'primary-fixed-dim': '#ffb3ae',
        'secondary-fixed-dim': '#eec14b',
        'primary-container': '#8b1e21',
        'on-primary-fixed': '#410005',
        'surface-container': '#f0eded',
        secondary: '#775a00',
        'error-container': '#ffdad6',
        'on-surface-variant': '#584140',
        // Traditional Vietnamese tokens from DESIGN.md
        'son-mai': '#8B1E21',
        'dong-co': '#C59B27',
        'tram-huong': '#3E2723',
        'muc-tau': '#262626',
        'giay-do': '#FAF7F2',
        'parchment-border': '#E6DFD5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        margin: '3rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'gutter-mobile': '0.75rem',
      },
      fontFamily: {
        serif: ['Playfair Display', 'serif'],
        sans: ['Roboto', 'Inter', 'Arial', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'title-lg': ['Roboto', 'sans-serif'],
        'title-md': ['Roboto', 'sans-serif'],
        'body-lg': ['Roboto', 'sans-serif'],
        'body-md': ['Roboto', 'sans-serif'],
        'body-sm': ['Roboto', 'sans-serif'],
        'label-lg': ['Roboto', 'sans-serif'],
        'label-md': ['Roboto', 'sans-serif'],
        'label-sm': ['Roboto', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['44px', { lineHeight: '54px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-md': ['36px', { lineHeight: '46px', fontWeight: '600' }],
        'display-md-mobile': ['26px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
      },
      boxShadow: {
        'antique-card': '0 4px 16px -2px rgba(62, 39, 35, 0.06), 0 1px 3px 0 rgba(62, 39, 35, 0.04)',
        'sticky-nav': '0 2px 8px rgba(43, 29, 22, 0.03)',
      },
    },
  },
  plugins: [],
};
